package books;

public enum Genre {
    FICTION, CONTEMPORARY, FANTASY, HISTORICAL, HORROR, HUMOR, MYSTERY, NONFICTION, ROMANCE, YOUNGADULT, SCIFI, THRILLER, MAGICALREALISM, PARANORMAL, ADULT, CHICKLIT, CRIME, ACTION, ADVENTURE;
}
